{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:43:26.148Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:44:39.037Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:45:35.833Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:46:40.116Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:47:17.671Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:48:02.834Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:48:29.509Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:55:10.733Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_userId_fkey\"","method":"POST","path":"/api/containers/updateStatus","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_userId_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:50:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:58:25.897Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:15:40.683Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:16:54.465Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:22:00.569Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-10T03:19:20.815Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T03:00:01.882Z"}
{"level":"error","message":"read ECONNRESET","method":"GET","path":"/api/containers/143/parcels","stack":"Error: read ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-11T03:00:34.827Z"}
{"level":"error","message":"connect ENETUNREACH 191.96.56.103:3306","method":"GET","path":"/api/containers/154/parcels","stack":"Error: connect ENETUNREACH 191.96.56.103:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)","timestamp":"2024-11-11T14:09:22.148Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T15:47:10.407Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T15:47:21.444Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:97:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-11T16:18:53.790Z"}
{"level":"error","message":"Error upserting parcel: permission denied for schema public","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: permission denied for schema public\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-12T00:18:50.797Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-12T01:40:16.562Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-12T15:20:25.585Z"}
{"level":"error","message":"Failed to fetch parcel data","method":"GET","path":"/api/parcels/hbl/CTE300824203973","stack":"Error: Failed to fetch parcel data\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:173:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T15:07:12.698Z"}
{"level":"error","message":"Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T17:47:23.351Z"}
{"level":"error","message":"Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T17:47:42.788Z"}
{"level":"error","message":"Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: null value in column \"userId\" of relation \"Event\" violates not-null constraint\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T17:48:27.929Z"}
{"level":"error","message":"Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T18:00:16.988Z"}
{"level":"error","message":"Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T18:01:29.844Z"}
{"level":"error","message":"Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-13T18:03:23.517Z"}
{"level":"error","message":"Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T18:18:20.922Z"}
{"level":"error","message":"Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting events: ON CONFLICT DO UPDATE command cannot affect row a second time\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T18:22:59.703Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-14T18:35:59.553Z"}
{"level":"error","message":"Sheet \"Sheet1\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Sheet \"Sheet1\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).\n    at createSheetNotFoundError (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:113:10)\n    at readXlsx (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:64:11)\n    at readXlsxFileContents (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileContents.js:13:25)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileNode.js:15:42\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T19:13:58.304Z"}
{"level":"error","message":"Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).\n    at createSheetNotFoundError (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:113:10)\n    at readXlsx (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:64:11)\n    at readXlsxFileContents (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileContents.js:13:25)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileNode.js:15:42\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T19:15:25.707Z"}
{"level":"error","message":"Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).\n    at createSheetNotFoundError (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:113:10)\n    at readXlsx (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:64:11)\n    at readXlsxFileContents (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileContents.js:13:25)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileNode.js:15:42\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T19:16:07.019Z"}
{"level":"error","message":"Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Sheet \"undefined\" not found in the *.xlsx file. Available sheets: \"Habana 2446\" (#1), \"Provincia 2446\" (#2).\n    at createSheetNotFoundError (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:113:10)\n    at readXlsx (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsx.js:64:11)\n    at readXlsxFileContents (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileContents.js:13:25)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\read-excel-file\\source\\read\\readXlsxFileNode.js:15:42\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-14T20:57:38.169Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-15T15:22:24.945Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-15T16:29:28.730Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-15T16:38:13.855Z"}
{"level":"error","message":"Error upserting events: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting events: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-15T17:09:19.299Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-15T17:13:11.616Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-15T17:24:50.871Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-18T14:10:55.549Z"}
{"level":"error","message":"Error upserting events: deadlock detected","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting events: deadlock detected\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-18T14:16:03.969Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-18T14:17:56.534Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-19T18:57:36.490Z"}
{"level":"error","message":"read ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: read ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-20T14:48:01.872Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-21T18:21:29.013Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-21T18:22:12.571Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-21T18:22:56.187Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-21T18:27:15.838Z"}
{"level":"error","message":"connect ETIMEDOUT","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: connect ETIMEDOUT\n    at PoolConnection._handleTimeoutError (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\lib\\connection.js:205:17)\n    at listOnTimeout (node:internal/timers:581:17)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-22T15:40:23.770Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-22T15:40:46.818Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-22T19:02:08.672Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-22T19:03:48.595Z"}
{"level":"error","message":"Error upserting events: deadlock detected","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting events: deadlock detected\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-26T14:06:46.009Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)","timestamp":"2024-11-26T14:14:54.693Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-26T14:15:50.601Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-26T14:25:02.584Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-26T14:25:22.213Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-12-02T15:11:07.066Z"}
{"level":"error","message":"write ECONNRESET","method":"POST","path":"/api/parcels/upload-excel","stack":"Error: write ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-02T15:11:17.060Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:139:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-02T17:38:49.357Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:146:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-02T17:40:07.419Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:136:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-02T17:43:15.624Z"}
{"level":"error","message":"client.messages.create(...).then(...).done is not a function","method":"POST","path":"/api/parcels/upload-excel","stack":"TypeError: client.messages.create(...).then(...).done is not a function\n    at sendSMSNotification (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\services\\twilio_notification_service.ts:14:4)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:164:22\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:28:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T15:55:02.290Z"}
{"level":"error","message":"client.messages.create(...).then(...).done is not a function","method":"POST","path":"/api/parcels/upload-excel","stack":"TypeError: client.messages.create(...).then(...).done is not a function\n    at sendSMSNotification (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\services\\twilio_notification_service.ts:14:4)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:164:22\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:28:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T15:56:58.125Z"}
{"level":"error","message":"client.messages.create(...).then(...).done is not a function","method":"POST","path":"/api/parcels/upload-excel","stack":"TypeError: client.messages.create(...).then(...).done is not a function\n    at sendSMSNotification (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\services\\twilio_notification_service.ts:14:4)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:164:22\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:28:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T15:57:29.534Z"}
{"level":"error","message":"client.messages.create(...).then(...).done is not a function","method":"POST","path":"/api/parcels/upload-excel","stack":"TypeError: client.messages.create(...).then(...).done is not a function\n    at sendSMSNotification (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\services\\twilio_notification_service.ts:14:4)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:164:22\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\controllers\\parcelController.ts:28:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T15:59:02.554Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"","method":"POST","path":"/api/parcels/upsert-events","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T16:16:41.472Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"","method":"POST","path":"/api/parcels/upsert-events","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T16:17:16.900Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_locationId_fkey\"","method":"POST","path":"/api/parcels/upsert-events","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_locationId_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T16:19:34.303Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_locationId_fkey\"","method":"POST","path":"/api/parcels/upsert-events","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_locationId_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-10T16:20:13.734Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"","method":"POST","path":"/api/parcels/upsert-events","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_hbl_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:49:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-12-12T02:34:06.639Z"}
