{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:43:26.148Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:44:39.037Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:94:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:45:35.833Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:46:40.116Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:47:17.671Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:48:02.834Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:48:29.509Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:96:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:55:10.733Z"}
{"level":"error","message":"Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_userId_fkey\"","method":"POST","path":"/api/containers/updateStatus","stack":"Error: Error upserting events: insert or update on table \"Event\" violates foreign key constraint \"Event_userId_fkey\"\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:50:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-08T18:58:25.897Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:15:40.683Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:16:54.465Z"}
{"level":"error","message":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1","method":"POST","path":"/api/containers/updateStatus","stack":"Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `createdAt` = '2024-08-26T04:00:00.000Z', `name` = 'SEGU5258722 2446', `serv...' at line 1\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-09T05:22:00.569Z"}
{"level":"error","message":"Error upserting parcel: FetchError: fetch failed","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: FetchError: fetch failed\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at processImmediate (node:internal/timers:454:9)","timestamp":"2024-11-10T03:19:20.815Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T03:00:01.882Z"}
{"level":"error","message":"read ECONNRESET","method":"GET","path":"/api/containers/143/parcels","stack":"Error: read ECONNRESET\n    at PromisePoolConnection.query (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\node_modules\\mysql2\\promise.js:94:22)\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:7:36\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_client.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-11T03:00:34.827Z"}
{"level":"error","message":"connect ENETUNREACH 191.96.56.103:3306","method":"GET","path":"/api/containers/154/parcels","stack":"Error: connect ENETUNREACH 191.96.56.103:3306\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)","timestamp":"2024-11-11T14:09:22.148Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T15:47:10.407Z"}
{"level":"error","message":"An error occurred while searching for packages. Please try again later.","method":"GET","path":"/api/parcels/search","stack":"Error: An error occurred while searching for packages. Please try again later.\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:127:11\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\mysql\\mysql_db.ts:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at runNextTicks (node:internal/process/task_queues:64:3)\n    at listOnTimeout (node:internal/timers:545:9)\n    at processTimers (node:internal/timers:519:7)","timestamp":"2024-11-11T15:47:21.444Z"}
{"level":"error","message":"Error signing in: Error signing in: Invalid login credentials","method":"POST","path":"/api/users/supabase/signin","stack":"Error: Error signing in: Error signing in: Invalid login credentials\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:97:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-11T16:18:53.790Z"}
{"level":"error","message":"Error upserting parcel: permission denied for schema public","method":"POST","path":"/api/parcels/import-events","stack":"Error: Error upserting parcel: permission denied for schema public\n    at C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:22:11\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\yosho\\Documents\\Panchito\\Tracking-CTEnvios\\backend-typescript\\src\\databases\\supabase\\supabase_db.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-11-12T00:18:50.797Z"}
